// ─────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by model/src/generate_predictions.py
// Source model : XGBoost (xgb_days_to_failure.json)
// Generated at : 2026-06-03 16:27
// DO NOT EDIT manually — re-run the script to refresh.
// ─────────────────────────────────────────────────────────────────────────

export type RiskStatus = "Critical" | "Warning" | "Watch" | "Normal";

export interface MachinePrediction {
  machineID: string;
  model: string;
  age: number;
  daysToFailure: number;
  volt: number;
  rotate: number;
  pressure: number;
  vibration: number;
  underMaintenance: boolean;
}

export function statusFromDays(days: number): RiskStatus {
  if (days < 7)  return "Critical";
  if (days < 14) return "Warning";
  if (days < 30) return "Watch";
  return "Normal";
}

export const STATUS_COLOR: Record<RiskStatus, string> = {
  Critical: "#d9534f",
  Warning:  "#e8a33d",
  Watch:    "#5fa8e8",
  Normal:   "#2fab6f",
};

export const MACHINES: MachinePrediction[] = [
  { machineID: "M001", model: "model3", age: 18, daysToFailure: 10.1, volt: 188.7, rotate: 540.8, pressure: 105.7, vibration: 42.0, underMaintenance: false },
  { machineID: "M002", model: "model4", age: 7, daysToFailure: 11.5, volt: 141.8, rotate: 487.3, pressure: 105.2, vibration: 46.4, underMaintenance: false },
  { machineID: "M003", model: "model3", age: 8, daysToFailure: 14.4, volt: 168.8, rotate: 554.1, pressure: 102.2, vibration: 42.7, underMaintenance: false },
  { machineID: "M004", model: "model3", age: 7, daysToFailure: 27.2, volt: 192.5, rotate: 460.0, pressure: 116.2, vibration: 38.7, underMaintenance: false },
  { machineID: "M005", model: "model3", age: 2, daysToFailure: 18.6, volt: 159.9, rotate: 437.9, pressure: 90.9, vibration: 37.9, underMaintenance: false },
  { machineID: "M006", model: "model3", age: 5, daysToFailure: 81.2, volt: 170.0, rotate: 450.0, pressure: 100.0, vibration: 40.0, underMaintenance: false },
  { machineID: "M007", model: "model3", age: 20, daysToFailure: 44.2, volt: 168.3, rotate: 450.9, pressure: 128.0, vibration: 45.7, underMaintenance: true },
  { machineID: "M008", model: "model3", age: 16, daysToFailure: 34.6, volt: 185.2, rotate: 500.8, pressure: 107.7, vibration: 31.3, underMaintenance: false },
  { machineID: "M009", model: "model4", age: 7, daysToFailure: 4.8, volt: 167.0, rotate: 284.6, pressure: 88.1, vibration: 44.2, underMaintenance: false },
  { machineID: "M010", model: "model3", age: 10, daysToFailure: 53.9, volt: 170.5, rotate: 449.2, pressure: 94.6, vibration: 44.9, underMaintenance: false },
  { machineID: "M011", model: "model2", age: 6, daysToFailure: 24.3, volt: 169.5, rotate: 396.2, pressure: 103.0, vibration: 48.3, underMaintenance: false },
  { machineID: "M012", model: "model3", age: 9, daysToFailure: 33.4, volt: 166.8, rotate: 408.5, pressure: 105.2, vibration: 36.5, underMaintenance: false },
  { machineID: "M013", model: "model1", age: 15, daysToFailure: 14.8, volt: 156.5, rotate: 405.7, pressure: 94.2, vibration: 39.1, underMaintenance: false },
  { machineID: "M014", model: "model3", age: 1, daysToFailure: 30.5, volt: 156.0, rotate: 445.7, pressure: 95.9, vibration: 39.5, underMaintenance: true },
  { machineID: "M015", model: "model3", age: 14, daysToFailure: 33.8, volt: 172.5, rotate: 410.9, pressure: 111.8, vibration: 38.1, underMaintenance: false },
  { machineID: "M016", model: "model1", age: 3, daysToFailure: 16.9, volt: 160.5, rotate: 421.5, pressure: 94.7, vibration: 42.1, underMaintenance: false },
  { machineID: "M017", model: "model1", age: 14, daysToFailure: 11.2, volt: 187.9, rotate: 436.5, pressure: 104.2, vibration: 45.7, underMaintenance: false },
  { machineID: "M018", model: "model3", age: 15, daysToFailure: 20.7, volt: 187.3, rotate: 479.0, pressure: 102.0, vibration: 40.6, underMaintenance: false },
  { machineID: "M019", model: "model3", age: 17, daysToFailure: 5.5, volt: 180.3, rotate: 495.9, pressure: 108.2, vibration: 44.1, underMaintenance: false },
  { machineID: "M020", model: "model2", age: 16, daysToFailure: 8.8, volt: 152.4, rotate: 513.2, pressure: 99.3, vibration: 36.1, underMaintenance: false },
  { machineID: "M021", model: "model2", age: 14, daysToFailure: 25.4, volt: 141.7, rotate: 353.9, pressure: 95.3, vibration: 29.7, underMaintenance: true },
  { machineID: "M022", model: "model1", age: 14, daysToFailure: 16.5, volt: 154.4, rotate: 461.2, pressure: 91.3, vibration: 41.9, underMaintenance: false },
  { machineID: "M023", model: "model1", age: 17, daysToFailure: 19.4, volt: 144.8, rotate: 394.2, pressure: 106.8, vibration: 43.1, underMaintenance: false },
  { machineID: "M024", model: "model1", age: 20, daysToFailure: 15.7, volt: 173.5, rotate: 482.2, pressure: 95.2, vibration: 45.7, underMaintenance: false },
  { machineID: "M025", model: "model4", age: 16, daysToFailure: 17.3, volt: 187.3, rotate: 548.3, pressure: 104.5, vibration: 49.3, underMaintenance: false },
  { machineID: "M026", model: "model3", age: 3, daysToFailure: 11.2, volt: 146.2, rotate: 446.6, pressure: 94.6, vibration: 37.5, underMaintenance: false },
  { machineID: "M027", model: "model3", age: 9, daysToFailure: 30.8, volt: 167.3, rotate: 420.6, pressure: 116.0, vibration: 43.5, underMaintenance: false },
  { machineID: "M028", model: "model4", age: 1, daysToFailure: 28.2, volt: 165.4, rotate: 511.2, pressure: 86.2, vibration: 35.4, underMaintenance: true },
  { machineID: "M029", model: "model4", age: 3, daysToFailure: 29.6, volt: 181.2, rotate: 407.1, pressure: 94.1, vibration: 44.2, underMaintenance: false },
  { machineID: "M030", model: "model3", age: 20, daysToFailure: 41.7, volt: 148.6, rotate: 363.0, pressure: 85.2, vibration: 43.2, underMaintenance: false },
  { machineID: "M031", model: "model1", age: 11, daysToFailure: 16.2, volt: 163.6, rotate: 357.3, pressure: 108.9, vibration: 44.6, underMaintenance: false },
  { machineID: "M032", model: "model4", age: 15, daysToFailure: 16.4, volt: 175.4, rotate: 523.4, pressure: 101.1, vibration: 35.2, underMaintenance: false },
  { machineID: "M033", model: "model3", age: 14, daysToFailure: 32.3, volt: 221.4, rotate: 421.3, pressure: 97.1, vibration: 38.4, underMaintenance: false },
  { machineID: "M034", model: "model4", age: 10, daysToFailure: 18.9, volt: 183.3, rotate: 351.5, pressure: 98.3, vibration: 31.0, underMaintenance: false },
  { machineID: "M035", model: "model1", age: 17, daysToFailure: 18.9, volt: 160.4, rotate: 524.5, pressure: 110.8, vibration: 44.2, underMaintenance: true },
  { machineID: "M036", model: "model4", age: 5, daysToFailure: 33.2, volt: 158.0, rotate: 430.3, pressure: 97.8, vibration: 36.7, underMaintenance: false },
  { machineID: "M037", model: "model1", age: 16, daysToFailure: 11.9, volt: 172.3, rotate: 418.6, pressure: 112.4, vibration: 39.7, underMaintenance: false },
  { machineID: "M038", model: "model4", age: 15, daysToFailure: 27.8, volt: 155.1, rotate: 461.0, pressure: 94.2, vibration: 42.5, underMaintenance: false },
  { machineID: "M039", model: "model4", age: 0, daysToFailure: 43.4, volt: 151.2, rotate: 498.8, pressure: 96.8, vibration: 34.9, underMaintenance: false },
  { machineID: "M040", model: "model2", age: 4, daysToFailure: 30.3, volt: 165.1, rotate: 443.1, pressure: 132.7, vibration: 36.3, underMaintenance: false },
  { machineID: "M041", model: "model4", age: 9, daysToFailure: 26.6, volt: 202.3, rotate: 441.4, pressure: 93.0, vibration: 33.0, underMaintenance: false },
  { machineID: "M042", model: "model1", age: 7, daysToFailure: 8.1, volt: 136.0, rotate: 483.8, pressure: 97.0, vibration: 43.2, underMaintenance: false },
  { machineID: "M043", model: "model3", age: 14, daysToFailure: 18.7, volt: 191.9, rotate: 401.6, pressure: 93.1, vibration: 42.0, underMaintenance: false },
  { machineID: "M044", model: "model4", age: 7, daysToFailure: 43.1, volt: 189.7, rotate: 422.4, pressure: 106.8, vibration: 37.6, underMaintenance: false },
  { machineID: "M045", model: "model3", age: 14, daysToFailure: 14.8, volt: 172.3, rotate: 345.0, pressure: 97.7, vibration: 45.3, underMaintenance: false },
  { machineID: "M046", model: "model4", age: 10, daysToFailure: 44.7, volt: 163.8, rotate: 430.1, pressure: 96.2, vibration: 40.7, underMaintenance: false },
  { machineID: "M047", model: "model2", age: 6, daysToFailure: 22.5, volt: 184.9, rotate: 418.4, pressure: 109.2, vibration: 38.6, underMaintenance: false },
  { machineID: "M048", model: "model4", age: 10, daysToFailure: 41.7, volt: 190.0, rotate: 468.2, pressure: 88.3, vibration: 38.8, underMaintenance: false },
  { machineID: "M049", model: "model1", age: 15, daysToFailure: 3.5, volt: 170.7, rotate: 447.7, pressure: 103.6, vibration: 54.4, underMaintenance: false },
  { machineID: "M050", model: "model4", age: 4, daysToFailure: 20.6, volt: 163.7, rotate: 415.6, pressure: 112.6, vibration: 46.9, underMaintenance: false },
  { machineID: "M051", model: "model4", age: 19, daysToFailure: 10.9, volt: 150.1, rotate: 360.5, pressure: 112.3, vibration: 41.3, underMaintenance: false },
  { machineID: "M052", model: "model3", age: 14, daysToFailure: 27.7, volt: 145.6, rotate: 446.2, pressure: 102.2, vibration: 34.4, underMaintenance: false },
  { machineID: "M053", model: "model3", age: 5, daysToFailure: 15.7, volt: 171.0, rotate: 445.1, pressure: 92.0, vibration: 35.8, underMaintenance: false },
  { machineID: "M054", model: "model2", age: 10, daysToFailure: 30.1, volt: 163.8, rotate: 436.4, pressure: 87.5, vibration: 29.6, underMaintenance: false },
  { machineID: "M055", model: "model3", age: 17, daysToFailure: 27.9, volt: 172.9, rotate: 392.2, pressure: 82.2, vibration: 45.6, underMaintenance: false },
  { machineID: "M056", model: "model1", age: 10, daysToFailure: 23.0, volt: 170.7, rotate: 363.0, pressure: 95.3, vibration: 36.6, underMaintenance: true },
  { machineID: "M057", model: "model4", age: 10, daysToFailure: 8.4, volt: 188.7, rotate: 493.2, pressure: 108.3, vibration: 41.1, underMaintenance: false },
  { machineID: "M058", model: "model1", age: 5, daysToFailure: 11.5, volt: 176.6, rotate: 464.4, pressure: 131.5, vibration: 45.1, underMaintenance: false },
  { machineID: "M059", model: "model3", age: 17, daysToFailure: 32.7, volt: 178.0, rotate: 512.3, pressure: 106.8, vibration: 34.7, underMaintenance: false },
  { machineID: "M060", model: "model4", age: 3, daysToFailure: 77.9, volt: 176.0, rotate: 548.0, pressure: 97.4, vibration: 44.3, underMaintenance: false },
  { machineID: "M061", model: "model4", age: 2, daysToFailure: 28.6, volt: 181.9, rotate: 367.1, pressure: 100.9, vibration: 36.6, underMaintenance: false },
  { machineID: "M062", model: "model4", age: 20, daysToFailure: 27.4, volt: 190.2, rotate: 455.4, pressure: 108.7, vibration: 36.1, underMaintenance: false },
  { machineID: "M063", model: "model4", age: 14, daysToFailure: 36.0, volt: 164.2, rotate: 499.7, pressure: 79.6, vibration: 42.6, underMaintenance: true },
  { machineID: "M064", model: "model3", age: 20, daysToFailure: 45.4, volt: 174.0, rotate: 388.9, pressure: 93.0, vibration: 40.8, underMaintenance: false },
  { machineID: "M065", model: "model3", age: 15, daysToFailure: 18.9, volt: 157.1, rotate: 429.4, pressure: 107.5, vibration: 53.3, underMaintenance: false },
  { machineID: "M066", model: "model4", age: 6, daysToFailure: 8.3, volt: 162.9, rotate: 459.3, pressure: 101.7, vibration: 42.7, underMaintenance: false },
  { machineID: "M067", model: "model4", age: 14, daysToFailure: 11.7, volt: 191.8, rotate: 480.8, pressure: 97.1, vibration: 41.1, underMaintenance: false },
  { machineID: "M068", model: "model3", age: 10, daysToFailure: 12.5, volt: 162.9, rotate: 492.1, pressure: 94.9, vibration: 49.3, underMaintenance: false },
  { machineID: "M069", model: "model2", age: 19, daysToFailure: 21.0, volt: 184.3, rotate: 432.8, pressure: 90.0, vibration: 32.3, underMaintenance: false },
  { machineID: "M070", model: "model3", age: 9, daysToFailure: 7.7, volt: 194.4, rotate: 517.9, pressure: 92.4, vibration: 27.8, underMaintenance: false },
  { machineID: "M071", model: "model2", age: 18, daysToFailure: 18.2, volt: 185.8, rotate: 412.1, pressure: 97.0, vibration: 34.2, underMaintenance: false },
  { machineID: "M072", model: "model4", age: 2, daysToFailure: 64.5, volt: 155.6, rotate: 413.1, pressure: 102.7, vibration: 41.4, underMaintenance: false },
  { machineID: "M073", model: "model2", age: 20, daysToFailure: 4.0, volt: 181.4, rotate: 431.9, pressure: 126.1, vibration: 37.1, underMaintenance: false },
  { machineID: "M074", model: "model4", age: 4, daysToFailure: 30.2, volt: 168.8, rotate: 561.6, pressure: 77.7, vibration: 42.2, underMaintenance: false },
  { machineID: "M075", model: "model3", age: 19, daysToFailure: 24.0, volt: 161.8, rotate: 467.6, pressure: 88.8, vibration: 33.3, underMaintenance: false },
  { machineID: "M076", model: "model2", age: 10, daysToFailure: 19.4, volt: 162.8, rotate: 528.1, pressure: 127.4, vibration: 32.6, underMaintenance: false },
  { machineID: "M077", model: "model2", age: 12, daysToFailure: 27.9, volt: 169.0, rotate: 441.0, pressure: 114.0, vibration: 42.0, underMaintenance: true },
  { machineID: "M078", model: "model4", age: 19, daysToFailure: 30.5, volt: 166.0, rotate: 504.5, pressure: 86.0, vibration: 41.3, underMaintenance: false },
  { machineID: "M079", model: "model3", age: 14, daysToFailure: 34.0, volt: 145.5, rotate: 469.9, pressure: 105.1, vibration: 30.3, underMaintenance: false },
  { machineID: "M080", model: "model3", age: 6, daysToFailure: 24.0, volt: 199.5, rotate: 502.6, pressure: 88.4, vibration: 32.7, underMaintenance: false },
  { machineID: "M081", model: "model4", age: 1, daysToFailure: 1.5, volt: 163.8, rotate: 386.8, pressure: 93.4, vibration: 36.8, underMaintenance: false },
  { machineID: "M082", model: "model3", age: 11, daysToFailure: 21.7, volt: 154.9, rotate: 396.2, pressure: 102.6, vibration: 26.9, underMaintenance: false },
  { machineID: "M083", model: "model4", age: 18, daysToFailure: 17.5, volt: 191.8, rotate: 467.9, pressure: 90.0, vibration: 35.1, underMaintenance: false },
  { machineID: "M084", model: "model3", age: 9, daysToFailure: 28.1, volt: 169.2, rotate: 405.3, pressure: 103.2, vibration: 36.6, underMaintenance: true },
  { machineID: "M085", model: "model1", age: 16, daysToFailure: 17.9, volt: 164.5, rotate: 389.7, pressure: 91.9, vibration: 39.7, underMaintenance: false },
  { machineID: "M086", model: "model3", age: 2, daysToFailure: 24.2, volt: 177.7, rotate: 398.8, pressure: 109.5, vibration: 36.6, underMaintenance: false },
  { machineID: "M087", model: "model2", age: 12, daysToFailure: 24.0, volt: 166.4, rotate: 488.8, pressure: 104.5, vibration: 40.3, underMaintenance: false },
  { machineID: "M088", model: "model4", age: 14, daysToFailure: 24.2, volt: 177.0, rotate: 452.6, pressure: 72.4, vibration: 41.3, underMaintenance: false },
  { machineID: "M089", model: "model3", age: 17, daysToFailure: 21.1, volt: 177.1, rotate: 365.9, pressure: 75.0, vibration: 47.2, underMaintenance: false },
  { machineID: "M090", model: "model2", age: 2, daysToFailure: 13.3, volt: 182.4, rotate: 407.0, pressure: 106.0, vibration: 37.1, underMaintenance: false },
  { machineID: "M091", model: "model4", age: 17, daysToFailure: 30.8, volt: 164.7, rotate: 474.0, pressure: 89.0, vibration: 43.1, underMaintenance: true },
  { machineID: "M092", model: "model1", age: 2, daysToFailure: 23.7, volt: 155.1, rotate: 366.4, pressure: 91.8, vibration: 46.6, underMaintenance: false },
  { machineID: "M093", model: "model3", age: 18, daysToFailure: 32.8, volt: 184.7, rotate: 386.6, pressure: 101.0, vibration: 40.1, underMaintenance: false },
  { machineID: "M094", model: "model2", age: 18, daysToFailure: 27.2, volt: 191.7, rotate: 472.2, pressure: 88.2, vibration: 39.0, underMaintenance: false },
  { machineID: "M095", model: "model2", age: 18, daysToFailure: 28.0, volt: 171.7, rotate: 390.4, pressure: 97.6, vibration: 31.3, underMaintenance: false },
  { machineID: "M096", model: "model2", age: 10, daysToFailure: 51.1, volt: 179.9, rotate: 425.3, pressure: 99.3, vibration: 41.2, underMaintenance: false },
  { machineID: "M097", model: "model2", age: 14, daysToFailure: 7.4, volt: 183.5, rotate: 370.4, pressure: 113.1, vibration: 45.8, underMaintenance: false },
  { machineID: "M098", model: "model2", age: 20, daysToFailure: 9.8, volt: 169.3, rotate: 389.5, pressure: 80.0, vibration: 42.3, underMaintenance: false },
  { machineID: "M099", model: "model1", age: 14, daysToFailure: 9.2, volt: 200.3, rotate: 388.4, pressure: 104.2, vibration: 30.7, underMaintenance: false },
  { machineID: "M100", model: "model4", age: 5, daysToFailure: 16.3, volt: 191.3, rotate: 335.9, pressure: 96.8, vibration: 45.6, underMaintenance: false }
];

export interface TrendPoint { label: string; value: number; }
export const RUL_TREND: TrendPoint[] = [
  { label: "Week 1", value: 20.9 },
  { label: "Week 2", value: 18.5 },
  { label: "Week 3", value: 16.3 },
  { label: "Week 4", value: 14.6 },
  { label: "Week 5", value: 10.4 },
  { label: "Week 6", value: 8.1 },
  { label: "Week 7", value: 4.8 },
  { label: "Week 8", value: 0.3 }
];

export const LAST_SYNC = "2015-12-26 07:00";
export const TOTAL_MACHINES = 100;

// Editable test machine — UI lets users tweak inputs and re-run the model.
export const TEST_MACHINE_ID = "M006";
export const M006_BASELINE: MachinePrediction = {
  machineID: "M006",
  model: "model3",
  age: 5,
  daysToFailure: 81.2,
  volt: 170.0,
  rotate: 450.0,
  pressure: 100.0,
  vibration: 40.0,
  underMaintenance: false,
};
